const types = {
    GET_PRODUCTS: 'GET_PRODUCTS',
    REMOVE_PRODUCTS_FROM_STORE: 'REMOVE_PRODUCTS_FROM_STORE',
    SELECT_SIZE: 'SELECT_SIZE',

    // Cart Reducer
    ADD_PRODUCTS_TO_CART: 'ADD_PRODUCTS_TO_CART',
    REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
    ADD_QUANTITY: 'ADD_QUANTITY'
}

export default types;